pipeline {
    agent any
    stages {
        stage('CleanUp') {
            steps {
                sh 'mvn -B -DskipTests clean  package'
            }
        }
        stage('Test') {
            steps {
                echo "mvn test"
            }
            post{
                always{
                    junit "target/surefire-reports/*.xml"
                }
            }
        }
        stage('Delivery'){
            steps{
                sh "./jenkins/scritps/deviler.sh"
            }
        }
    }
}
