pipeline {
    agent any
    tools{
        maven '3.9.1'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean  package'
            }
        }
    stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Delivery'){
            steps{
                sh './jenkins/scritps/deviler.sh'
            }
        }
    }
}
